name: Run Crisiscompass every 24 hours

on:
  # Trigger the workflow every 24 hours
  schedule:
    - cron: '0 0 * * *'  # This is 12:00 AM UTC every day
  # Allow manual triggering via GitHub UI
  workflow_dispatch:

jobs:
  update-json-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.10  # Changed to a valid version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the Python script
      run: python crisiscompass.py
