name: Run Crisiscompass every 24 hours

on:
  schedule:
    - cron: '0 0 * * *'  # This cron expression runs every day at midnight UTC
  workflow_dispatch:  # Allows for manual triggering of the workflow if needed

jobs:
  run-script:
    runs-on: ubuntu-latest  # This will run the job on the latest Ubuntu environment
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This step checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v3  # This step sets up Python in the GitHub Actions environment
      with:
        python-version: '3.10'  # Use Python version 3.10 (adjust if needed)

    - name: Install dependencies
      run: |
        pip install --upgrade pip  # Upgrade pip to the latest version
        pip install -r requirements.txt  # Install the dependencies from the requirements.txt

    - name: Run Crisiscompass Script
      run: python src/crisiscompass.py  # This runs your Python script from the src folder
